### ISSUE TITLE
З'являється повідомлення про помилку "User not found!" у формі реєстрації після введення валідних даних.

### ISSUE THREAD

**Issue by larazayec** [larazayec/web.test#2]
1. Відкрити сайт https://localhost:5001/
2. Ввести в поле "Login" валідні дані "Alex".
3. Ввести в поле "Password" валідні дані "12345678".
4. Натиснути кнопку "Login".
5. Звернути увагу на інформаційне повідомлення.
Очікуваний результат: Відбувається реєстрація нового користувача.
Фактичний результат: З'являється повідомлення про помилку "User not found!", реєстрація нового користувача не відбувається.

**Comment by varajan** [comment]
Not a bug, works as designed.
