### ISSUE TITLE
З'являється повідомлення про помилку "Incorrect password!" у формі реєстрації після введення невалідного логіну.

### ISSUE THREAD

**Issue by larazayec** [larazayec/web.test#3]
1. Відкрити сайт https://localhost:5001/
2. Ввести в поле "Login" невалідний логін "Test".
3. Ввести в поле "Password" валідний пароль "newyork1".
4. Натиснути кнопку "Login".
5. Звернути увагу на інформаційне повідомлення.

Фактичний результат: З'являється інформаційне повідомлення "Incorrect password!".
Очікуваний результат: З'являється інформаційне повідомлення "Incorrect user name!".

**Comment by varajan** [comment]
Please update the test-case
