### ISSUE TITLE
Не відбувається вхід в систему в формі реєстрації після введення валідного логіну у верхньому регістрі.

### ISSUE THREAD

**Issue by larazayec** [larazayec/web.test#4]
1. Перейти на сайт https://localhost:5001/
2. Ввести валідні дані в верхньому регістрі "TEST" в поле "Login".
3. Ввести валідні дані "newyork1" в поле "Password".
4. Натиснути кнопку "Login".
5. Звернути увагу на повідомлення на екрані.

Фактичний результат: Не відбувається вхід в систему в формі реєстрації після введення валідного логіну у верхньому регістрі. З'являється інформаційне повідомлення про помилку.
Очікуваний результат: Відбувається вхід в систему в формі реєстрації після введення валідного логіну у верхньому регістрі.

**Comment by varajan** [comment]
Fixed. Please re-check.
