### ISSUE TITLE
Помилка у назві поля паролю "Pasword"  у формі реєстрації.

### ISSUE THREAD

**Issue by larazayec** [larazayec/web.test#5]
1. Відкрити сайт https://localhost:5001
2. Звернути увагу на назву поля паролю"Pasword".

Фактичний результат: Помилка у назві поля паролю "Pasword"  у формі реєстрації.
Очікуваний результат: Назва поля паролю "Password" у полі реєстрації.

**Comment by varajan** [comment]
Fixed, please do git pull and re-start the web-site.
